server:
  port: 3000
  origin: https://99.79.89.235/ ##https://99.79.89.235 ##http://127.0.0.1:80 ##http://localhost:4200
  localhost: https://99.79.89.235/api/ ## http://99.79.89.235:3000/api/ http://localhost:3000/api/
  domain: https://rodriguesfranceschini.com/
  domain_api: https://rodriguesfranceschini.com/api/
  domain_www: https://www.rodriguesfranceschini.com/

db:
  type: 'postgres'
  port: 5432
  database: 'rflawyers'
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  synchronize: true

jwt:
  secret: 'topSecret42'
  expiresIn: '7d'

person-jwt:
  expiresIn: '30d'

email-sender:
  host: 'smtp.gmail.com'
  port: 465
  secure: true
  tls: true
  user: 'helem@helemfranceschini.com'
  pass: 'Curso2021'
  from: 'Franceschini Advogados Associados'
  live: true