server:
  origin: http://127.0.0.1:80 ##http://localhost:4200

db:
  synchronize: false

email-sender:
  host: 'smtp.gmail.com'
  port: 465
  secure: true
  tls: true
  user: 'jddedrick42@gmail.com'
  pass: 'r2d2paradoxo42'
  from: 'Edrick Manoel'
  live: true