server:
  origin: https://99.79.89.235/ ##https://99.79.89.235 ##http://127.0.0.1:80 ##http://localhost:4200
  localhost: http://localhost:3000/api/

db:
  synchronize: false

email-sender:
  host: 'smtp.gmail.com'
  port: 465
  secure: true
  tls: true
  user: 'jddedrick42@gmail.com'
  pass: 'r2d2paradoxo42'
  from: 'Rodrigues & Franceschini'
  live: true